lapuelltwo, alpha=0.5, sample size=380000
#########################################
Traceback (most recent call last):
  File "/home1/jongminm/LDPUts/experiment/meeting/071424/conti_scale_d5/conti_scale_d5_lapuelltwo_n380000_priv0.5.py", line 97, in <module>
    device
  File "/home1/jongminm/LDPUts/server.py", line 102, in load_private_data_multinomial
    self.data_y_square_colsum = self.data_y.square().sum(1)
RuntimeError: CUDA out of memory. Tried to allocate 2.90 GiB (GPU 0; 11.17 GiB total capacity; 8.70 GiB already allocated; 2.02 GiB free; 8.71 GiB reserved in total by PyTorch)
